package org.firstinspires.ftc.teamcode.opmodes.autonomous;

import com.pedropathing.follower.Follower;
import com.pedropathing.geometry.BezierCurve;
import com.pedropathing.geometry.BezierLine;
import com.pedropathing.geometry.Pose;
import com.pedropathing.paths.PathBuilder;
import com.pedropathing.paths.PathChain;

public class BlueClassifierAutoGeneratedPaths {


        public static PathChain line1(Follower follower) {
            return follower.pathBuilder()
                    .addPath(
                            new BezierLine(new Pose(26.000, 129.000), new Pose(59.036, 108.578))
                    )
                    .setLinearHeadingInterpolation(Math.toRadians(-44), Math.toRadians(-35))
                    .build();
        }

        public static PathChain line2(Follower follower) {
            return follower.pathBuilder()
                    .addPath(
                            new BezierCurve(
                                    new Pose(59.036, 108.578),
                                    new Pose(73.278, 98.597),
                                    new Pose(76.078, 87.398),
                                    new Pose(63.418, 85.085),
                                    new Pose(19.354, 83.868)
                            )
                    )
                    .setTangentHeadingInterpolation()
                    .build();
        }

        public static PathChain line3(Follower follower) {
            return follower.pathBuilder()
                    .addPath(
                            new BezierCurve(
                                    new Pose(19.354, 83.868),
                                    new Pose(75.347, 82.529),
                                    new Pose(59.036, 108.700)
                            )
                    )
                    .setLinearHeadingInterpolation(Math.toRadians(180), Math.toRadians(-35))
                    .build();
        }

        public static PathChain line4(Follower follower) {
            return follower.pathBuilder()
                    .addPath(
                            new BezierCurve(
                                    new Pose(59.036, 108.700),
                                    new Pose(94.336, 84.964),
                                    new Pose(51.855, 62.688),
                                    new Pose(97.258, 59.645),
                                    new Pose(18.259, 59.888)
                            )
                    )
                    .setTangentHeadingInterpolation()
                    .build();
        }

        public static PathChain line5(Follower follower) {
            return follower.pathBuilder()
                    .addPath(
                            new BezierLine(new Pose(18.259, 59.888), new Pose(59.036, 108.700))
                    )
                    .setLinearHeadingInterpolation(Math.toRadians(180), Math.toRadians(-44))
                    .build();
        }

        public static PathChain line6(Follower follower) {
            return follower.pathBuilder()
                    .addPath(
                            new BezierLine(new Pose(59.036, 108.700), new Pose(20.693, 69.992))
                    )
                    .setLinearHeadingInterpolation(Math.toRadians(-44), Math.toRadians(0))
                    .build();
        }
}
